### ISSUE TITLE
How to validate card details

### ISSUE THREAD

**Issue by ashishbansal-kmc** [BenMorel/Paybox#1]
Please provide me sandbox url of paybox and also tell me how to validate card details either at front end or backend.

**Comment by BenMorel** [comment]
Hi, this is not an official Paybox library; please ask Paybox for your sandbox URL and credentials.

I have hardcoded a few URL endpoints, but your mileage may vary:
https://github.com/BenMorel/Paybox/search?utf8=%E2%9C%93&q=PREPROD&type=

As for the credit card validation, this is not something this repository will provide!
