### ISSUE TITLE
PayboxSystem Doc

### ISSUE THREAD

**Issue by Lynesth** [BenMorel/Paybox#2]
Bonjour,

Je n'arrive vraiment pas à comprendre comment la partie PayboxSystem est censée fonctionner. Est-ce qu'il manque du code ou je suis juste aveugle ?

Si c'est moi, est-ce qu'il serait possible d'avoir un bout de code d'exemple ?

Merci beaucoup !

**Comment by BenMorel** [comment]
Bonjour, `PayboxSystem` permet de générer les paramètres du formulaire pour appeler la page de paiement.

Votre confusion vient peut-être du fait que le paramètre `$url` n'est utilisé nulle part, je viens de le supprimer du constructeur de `PayboxSystem`, il est inutile ici car uniquement nécessaire pour l'attribut `action` du formulaire.

Voici un exemple d'utilisation :

```php
// Utilisez les paramètres (site, rang, identifiant, clé HMAC) qui vous ont été fournis
$paybox = new Paybox(...);
$payboxSystem = new PayboxSystem($paybox);

// Ces paramètres dépendent du panier que vous souhaitez faire payer
$amount = new Money('12.34', 'EUR');
$reference = 'ORDER-123456';
$email = 'client@example.com';

// Créez une requête avec ces paramètres
$payboxSystemRequest = new PayboxSystemRequest($amount, $reference, $email);

// Optionnellement, personnalisez la requête avec l'URL de retour sur votre site, etc.
// Voir la liste des méthodes de PayboxSystemRequest
$payboxSystemRequest->setSuccessUrl('https://example.com/success');
$payboxSystemRequest->setFailureUrl('https://example.com/failure');

// Et voici les paramètres pour notre formulaire
$parameters = $payboxSystem->getPostParameters($payboxSystemRequest);
```

Le choix de l'URL où poster le formulaire dépend :

- de votre prestataire : Paybox, ou E-Transactions du Crédit Agricole
- du type de page de paiement souhaité : classique, mobile ou iframe
- du serveur :
    - en production : normal ou backup
    - en développement : preprod

Toutes les constantes sont listées dans la classe `PayboxSystem`.

Pour créer votre formulaire, il suffit maintenant de faire :

```html
<!-- Utilisez la constante souhaitée -->
<form method="POST" action="<?= PayboxSystem::PAYBOX_PREPROD_URL; ?>">
    <?php foreach ($parameters as $key => $value): ?>
        <input type="hidden" name="<?= $key; ?>" value="<?= htmlspecialchars($value); ?>">
    <?php endforeach; ?>
    <input type="submit" value="Payer">
</form>
```

En espérant que cela réponde à votre question ! Je ferme cette issue, n'hésitez pas à commenter si vous rencontrez un problème.

**Comment by Lynesth** [comment]
Super merci !
